name: Autoremove Labels

on:
  issues:
    types: [closed, opened]
  pull_request_target:
    types: [closed]

jobs:
  community_check:
    uses: ./.github/workflows/community-check.yml
    secrets: inherit

  RemoveNeedsTriageFromMaintainers:
    needs: community_check
    if: github.event.action == 'opened' && needs.community_check.outputs.maintainer == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Remove needs-triage label from member's Issues
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        with:
          labels: |
            needs-triage

  RemoveTriagingLabelsFromClosedIssueOrPR:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Remove triaging labels from closed issues and PRs
        uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        with:
          labels: |
            needs-triage
            waiting-response
