name: CDKTF Documentation
on:
  schedule:
    - cron: "0 0 * * WED"
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  generateToken:
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.generate_token.outputs.token }}
    steps:
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.APP_ID }}
          installation_retrieval_mode: id
          installation_retrieval_payload: ${{ secrets.INSTALLATION_ID }}
          private_key: ${{secrets.APP_PEM }}

  cdktfDocs:
    needs:
      - generateToken
    uses: hashicorp/terraform-cdk/.github/workflows/registry-docs-pr-based.yml@304e2507209c9657135dc7b4b7ee68030327468f
    secrets:
      GH_PR_TOKEN: ${{ needs.generateToken.outputs.token }}
    with:
      providerFqn: "hashicorp/aws"
      languages: "typescript,python"
      files: "d/*.html.markdown,r/*.html.markdown"
      parallelFileConversions: 1
      maxRunners: 20
      cdktfRegistryDocsVersion: "1.14.2"
