name: Dependency Checks

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request_target:

jobs:
  community_check:
    uses: ./.github/workflows/community-check.yml
    secrets: inherit

  changes:
    needs: community_check
    name: Filter Changes
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: dorny/paths-filter@4512585405083f25c027a35db413c2b3b9006d50
        if: github.event_name == 'pull_request_target' && needs.community_check.outputs.maintainer == 'false'
        id: filter
        with:
          filters: |
            changed:
              - .ci/providerlint/**
              - go.mod
              - go.sum

  comment:
    needs: changes
    if: needs.changes.outputs.changed == 'true'
    name: Comment
    runs-on: ubuntu-latest
    steps:
      - name: Find Existing PR Comment
        id: prc
        uses: peter-evans/find-comment@034abe94d3191f9c89d870519735beae326f2bdb
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: "Please note that typically Go dependency changes"
      - run: echo ${{ steps.prc.outputs.comment-id }}
      - name: PR Comment
        if: steps.prc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@3383acd359705b10cb1eeef05c0e88c056ea4666
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |-
            Thank you for your contribution! :rocket:

            Please note that typically Go dependency changes are handled in this repository by dependabot or the maintainers. This is to prevent pull request merge conflicts and further delay reviews of contributions. Remove any changes to the `go.mod` or `go.sum` files and commit them into this pull request.

            Additional details:

            * Check [open pull requests with the `dependencies` label](https://github.com/hashicorp/terraform-provider-aws/pulls?q=is%3Aopen+is%3Apr+label%3Adependencies) to view other dependency updates.
            * If this pull request includes an update the AWS Go SDK (or any other dependency) version, only updates submitted via dependabot will be merged. This pull request will need to remove these changes and will need to be rebased after the existing dependency update via dependabot has been merged for this pull request to be reviewed.
            * If this pull request is for supporting a new AWS service:
              * Ensure the new AWS service changes are following the [Contributing Guide section on new services](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#new-service), in particular that the dependency addition and initial provider support are in a separate pull request from other changes (e.g. new resources). Contributions not following this item will not be reviewed until the changes are split.
              * If this pull request is already a separate pull request from the above item, you can ignore this message.

  go_mod:
    name: go mod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version-file: go.mod
      - name: go mod
        run: |
          echo "==> Checking source code with go mod tidy..."
          go mod tidy
          git diff --exit-code -- go.mod go.sum || \
            (echo; echo "Unexpected difference in go.mod/go.sum files. Run 'go mod tidy' command or revert any go.mod/go.sum changes and commit."; exit 1)
