name: Documentation Checks
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - .ci/.markdownlinkcheck.json
      - .markdownlint.yml
      - .github/workflows/documentation.yml
      - docs/**
      - go.mod

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    env:
      UV_THREADPOOL_SIZE: 128
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: YakDriver/md-check-links@9044b7162323b91150cef35355e1a3514564aa82
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.ci/.markdownlinkcheck.json'
          folder-path: 'docs'
          file-extension: '.md'
          base-branch: "main"
          check-modified-files-only: "yes"
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb
        with:
          args: 'docs'
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9
        with:
          go-version-file: go.mod
      - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8
        continue-on-error: true
        timeout-minutes: 2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-pkg-mod-${{ hashFiles('go.sum') }}
      - run: cd .ci/tools && go install github.com/client9/misspell/cmd/misspell
      - run: misspell -error -source text docs/
