name: TeamCity Config Generator
on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .teamcity/**

jobs:
  validate-teamcity-config:
    name: Validate TeamCity Configuration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11
          cache: maven
      - name: Build TeamCity Configuration
        run: |
          cd .teamcity
          mvn org.jetbrains.teamcity:teamcity-configs-maven-plugin:generate
