name: Issue Comment Created Triage

on:
  issue_comment:
    types: [created]

jobs:
  community_check:
    uses: ./.github/workflows/community-check.yml
    secrets: inherit

  issue_comment_triage:
    needs: community_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0
        if: github.event_name == 'issue_comment' && needs.community_check.outputs.maintainer == 'false'
        with:
          labels: |
            stale
            waiting-response
